
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "ExtThemeNeptune": "../../ext/packages/ext-theme-neptune/overrides",
  "Simplereg": "../../app",
  "Ext": "../../ext/src",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Simplereg.view.PersonList": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Simplereg.view.RelativeCreate": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Simplereg.view.override.ContactDelete": [],
  "Ext.ux.DataView.DragSelector": [],
  "Simplereg.store.Genders": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Simplereg.store.ContactTypes": [],
  "Simplereg.view.override.PersonData": [],
  "Simplereg.view.ContactDelete": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Simplereg.model.RelativePerson": [],
  "Simplereg.store.Relations": [],
  "Simplereg.view.override.PersonCreate": [],
  "Ext.ux.PreviewPlugin": [],
  "Simplereg.store.QueryPeople": [],
  "Simplereg.view.RelativeDelete": [],
  "Simplereg.view.PersonData": [],
  "Simplereg.store.RelativePeople": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Simplereg.controller.override.Common": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "ExtThemeNeptune.panel.Table": [],
  "Simplereg.view.override.PersonDetail": [],
  "Ext.ux.event.Recorder": [],
  "Simplereg.store.Contacts": [],
  "Simplereg.view.override.PersonUpdate": [],
  "Simplereg.view.override.PersonDelete": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Simplereg.model.Contact": [],
  "Ext.ux.TabScrollerMenu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [],
  "Simplereg.view.PersonCreate": [],
  "Ext.ux.form.SearchField": [],
  "Simplereg.view.PersonContacts": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Simplereg.view.RelativeUpdate": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Simplereg.model.PersonIdentity": [],
  "Simplereg.view.override.RelativeCreate": [],
  "Ext.ux.TreePicker": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Simplereg.store.People": [],
  "Simplereg.view.ContactCreate": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Simplereg.view.override.PersonList": [],
  "Simplereg.store.RelativeTypes": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Simplereg.view.Viewport": [],
  "Simplereg.model.Relative": [],
  "Simplereg.view.override.PersonSelect": [],
  "Ext.ux.FieldReplicator": [],
  "Simplereg.view.override.ContactCreate": [],
  "Simplereg.view.override.PersonContacts": [],
  "ExtThemeNeptune.panel.Panel": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Simplereg.model.Country": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Simplereg.view.Page": [],
  "Simplereg.view.PersonUpdate": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Simplereg.controller.Common": [],
  "Simplereg.view.override.PersonRelatives": [],
  "Simplereg.model.Person": [],
  "Ext.ux.GMapPanel": [],
  "Simplereg.view.PersonSelect": [],
  "Simplereg.store.Relatives": [],
  "Simplereg.view.override.PersonSearch": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Simplereg.view.override.RelativeDelete": [],
  "Simplereg.view.PersonSearch": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "Simplereg.view.ContactUpdate": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Simplereg.store.Countries": [],
  "Simplereg.view.PersonRelatives": [],
  "Simplereg.view.override.ContactUpdate": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Simplereg.view.override.RelativeUpdate": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Simplereg.view.PersonDetail": [],
  "Simplereg.view.PersonDelete": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Simplereg.view.override.Page": [],
  "Ext.ux.grid.FiltersFeature": [],
  "ExtThemeNeptune.Component": []
});
Ext.ClassManager.addNameAliasMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Simplereg.view.PersonList": [
    "widget.personlist"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Simplereg.view.RelativeCreate": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Simplereg.view.override.ContactDelete": [],
  "Ext.ux.DataView.DragSelector": [],
  "Simplereg.store.Genders": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Simplereg.store.ContactTypes": [],
  "Simplereg.view.override.PersonData": [],
  "Simplereg.view.ContactDelete": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Simplereg.model.RelativePerson": [],
  "Simplereg.store.Relations": [],
  "Simplereg.view.override.PersonCreate": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Simplereg.store.QueryPeople": [],
  "Simplereg.view.RelativeDelete": [],
  "Simplereg.view.PersonData": [
    "widget.persondata"
  ],
  "Simplereg.store.RelativePeople": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Simplereg.controller.override.Common": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "ExtThemeNeptune.panel.Table": [],
  "Simplereg.view.override.PersonDetail": [],
  "Ext.ux.event.Recorder": [],
  "Simplereg.store.Contacts": [],
  "Simplereg.view.override.PersonUpdate": [],
  "Simplereg.view.override.PersonDelete": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Simplereg.model.Contact": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Simplereg.view.PersonCreate": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Simplereg.view.PersonContacts": [
    "widget.personcontacts"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Simplereg.view.RelativeUpdate": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Simplereg.model.PersonIdentity": [],
  "Simplereg.view.override.RelativeCreate": [],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Simplereg.store.People": [],
  "Simplereg.view.ContactCreate": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "ExtThemeNeptune.menu.Menu": [],
  "Ext.ux.BoxReorderer": [],
  "Simplereg.view.override.PersonList": [],
  "Simplereg.store.RelativeTypes": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Simplereg.view.Viewport": [],
  "Simplereg.model.Relative": [],
  "Simplereg.view.override.PersonSelect": [],
  "Ext.ux.FieldReplicator": [],
  "Simplereg.view.override.ContactCreate": [],
  "Simplereg.view.override.PersonContacts": [],
  "ExtThemeNeptune.panel.Panel": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Simplereg.model.Country": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Simplereg.view.Page": [],
  "Simplereg.view.PersonUpdate": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Simplereg.controller.Common": [],
  "Simplereg.view.override.PersonRelatives": [],
  "Simplereg.model.Person": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Simplereg.view.PersonSelect": [
    "widget.personselect"
  ],
  "Simplereg.store.Relatives": [],
  "Simplereg.view.override.PersonSearch": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Simplereg.view.override.RelativeDelete": [],
  "Simplereg.view.PersonSearch": [],
  "ExtThemeNeptune.layout.component.Dock": [],
  "Simplereg.view.ContactUpdate": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Simplereg.store.Countries": [],
  "Simplereg.view.PersonRelatives": [
    "widget.personrelatives"
  ],
  "Simplereg.view.override.ContactUpdate": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Simplereg.view.override.RelativeUpdate": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Simplereg.view.PersonDetail": [
    "widget.persondetail"
  ],
  "Simplereg.view.PersonDelete": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Simplereg.view.override.Page": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "ExtThemeNeptune.Component": []
});
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/Component.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Panel.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/picker/Month.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Table.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/menu/Menu.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/menu/Separator.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/panel/Tool.js");
Ext.Loader.loadScript("../../ext/packages/ext-theme-neptune/overrides/tab/Tab.js");
